//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Betty
{
    using System;
    using System.Collections.Generic;
    
    public partial class CsgoBets
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int FirstTeamId { get; set; }
        public int SecondTeamId { get; set; }
        public int WinnerTeamId { get; set; }
        public double Chance { get; set; }
        public bool IsTrue { get; set; }
    }
}
