//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Betty
{
    using System;
    using System.Collections.Generic;
    
    public partial class CsgoMatch
    {
        public int Id { get; set; }
        public int FirstTeamId { get; set; }
        public int SecondTeamId { get; set; }
        public int FirstScore { get; set; }
        public int SecondScore { get; set; }
        public string Map { get; set; }
        public System.DateTime Date { get; set; }
        public string Url { get; set; }
        public Nullable<int> FirstPoints { get; set; }
        public Nullable<int> SecondPoints { get; set; }
    }
}
