//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Betty
{
    using System;
    using System.Collections.Generic;
    
    public partial class CsgoTeam
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public string LogoUrl { get; set; }
        public int Points { get; set; }
        public string Name { get; set; }
    }
}
